const { readDB, writeDB, FILES } = require('../config/database');

// Listar ONGs
const getAllOngs = (req, res) => {
  const ongs = readDB(FILES.ongs);
  res.json(ongs);
};

// Obter ONG específica
const getOngById = (req, res) => {
  const ongs = readDB(FILES.ongs);
  const ong = ongs.find(o => o.id === req.params.id);
  if (!ong) return res.status(404).json({ error: 'ONG não encontrada' });
  res.json(ong);
};

// Criar ONG
const createOng = async (req, res) => {
  try {
    const bcrypt = require('bcryptjs');
    const { name, address, phone, email, complement, cep, cnpj, state, city } = req.body;
    
    // Validar campos obrigatórios
    if (!name || !email || !phone || !address || !cnpj || !state || !city) {
      return res.status(400).json({ error: 'Campos obrigatórios faltando' });
    }

    const users = require('../config/database').readDB(require('../config/database').FILES.users);
    const ongs = require('../config/database').readDB(require('../config/database').FILES.ongs);

    // Verificar se email já existe
    if (users.find(u => u.email === email)) {
      return res.status(400).json({ error: 'Email já cadastrado' });
    }

    // Gerar senha automática
    const autoGeneratedPassword = Math.floor(100000 + Math.random() * 900000).toString();
    const hashedPassword = await bcrypt.hash(autoGeneratedPassword, 10);

    // Criar usuário
    const newUser = {
      id: Date.now().toString(),
      email,
      password: hashedPassword,
      name,
      userType: 'ong',
      phone,
      address,
      createdAt: new Date().toISOString()
    };

    users.push(newUser);
    require('../config/database').writeDB(require('../config/database').FILES.users, users);

    // Criar perfil da ONG
    const newOng = {
      id: newUser.id,
      userId: newUser.id,
      name,
      address,
      phone,
      email,
      complement: complement || '',
      cep: cep || '',
      cnpj,
      state,
      city,
      services: [],
      jovens: [],
      stats: { totalServices: 0, activeJovens: 0, rating: 0 },
      createdAt: new Date().toISOString()
    };

    ongs.push(newOng);
    require('../config/database').writeDB(require('../config/database').FILES.ongs, ongs);
    
    res.json({ 
      ...newOng, 
      autoGeneratedPassword,
      message: 'ONG criada com sucesso! Guarde a senha gerada.' 
    });
  } catch (error) {
    console.error('Erro ao criar ONG:', error);
    res.status(500).json({ error: error.message });
  }
};

// Atualizar ONG
const updateOng = (req, res) => {
  const ongs = readDB(FILES.ongs);
  const index = ongs.findIndex(o => o.id === req.params.id);
  if (index === -1) return res.status(404).json({ error: 'ONG não encontrada' });

  ongs[index] = { ...ongs[index], ...req.body, id: req.params.id };
  writeDB(FILES.ongs, ongs);
  res.json(ongs[index]);
};

// Deletar ONG
const deleteOng = (req, res) => {
  try {
    const ongs = readDB(FILES.ongs);
    const jovens = readDB(FILES.jovens);
    const index = ongs.findIndex(o => o.id === req.params.id);
    
    if (index === -1) return res.status(404).json({ error: 'ONG não encontrada' });

    // Desvincular jovens da ONG
    const updatedJovens = jovens.map(j => 
      j.ongId === req.params.id ? { ...j, ongId: null } : j
    );
    writeDB(FILES.jovens, updatedJovens);

    // Remover ONG
    ongs.splice(index, 1);
    writeDB(FILES.ongs, ongs);
    
    res.json({ message: 'ONG deletada com sucesso' });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

// Vincular jovem à ONG
const addJovemToOng = (req, res) => {
  const { jovemId } = req.body;
  const ongs = readDB(FILES.ongs);
  const jovens = readDB(FILES.jovens);

  const ong = ongs.find(o => o.id === req.params.id);
  const jovem = jovens.find(j => j.id === jovemId);

  if (!ong || !jovem) return res.status(404).json({ error: 'ONG ou Jovem não encontrado' });

  if (!ong.jovens.includes(jovemId)) {
    ong.jovens.push(jovemId);
    writeDB(FILES.ongs, ongs);
  }

  jovem.ongId = req.params.id;
  writeDB(FILES.jovens, jovens);

  res.json({ message: 'Jovem vinculado com sucesso', ong, jovem });
};

module.exports = {
  getAllOngs,
  getOngById,
  createOng,
  updateOng,
  deleteOng,
  addJovemToOng
};
